name: Publish

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Publish
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build image and push to GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          dafuemu/app:latest
          dafuemu/app:1.0.0
          ghcr.io/dafuemu/app:latest
          ghcr.io/dafuemu/app:1.0.0
